all:
  theme:
    # Disable/Enable theming globally
    enabled:           true
    
    # Turn on or off the web debug toolbar
    web_debug:         true

    # Options to help the correct theme to be chosen
    controller_options:
      default_theme:     ~                 # Configure the default theme to render
      admin_theme:       ~                 # Configure the theme to render for "admin" modules
      
      modules:    []                       # Specify an array of modules and the theme that each should use
        # my_module:     theme_name
      routes:     []                       # Specify an array of routes and the theme that each should use
        # my_route:      theme_name

      # Configure whether or not to allow the theme to be changed with a 
      # parameter in the url named sf_theme. Example: ?sf_theme=wordpress_default
      # The value will also be remembered in the users session
      allow_changing_theme_by_url: true
      theme_request_parameter_name: sf_theme

    theme_class:       sfTheme             # Class that represents an individual theme
    manager_class:     sfThemeManager      # Class that handles the switching of themes
    controller_class:  sfThemeController   # Class that handles which theme should be chosen
    toolkit_class:     sfThemeToolkit      # class that handles a few behind-the-scenes tasks

    # Caching is used to cache the paths to all the layouts in an app
    cache:
      enabled:  true
      class:    sfFileCache
      options:
        cache_dir:  <?php echo sfConfig::get('sf_app_cache_dir') ?>/theme

    themes:
      # my_theme:
      #   layout:   my_theme               # The name of the layout file to use
      #   javascripts: [my_file.js]        # Array of javascripts for this theme
      #   stylesheets: [theme_styles.css]  # Array of stylesheets for this theme
      #   callables:
      #     - [sfSympalToolkit, useJQuery]
      #   enabled: false                   # Enable/disable the theme [default=true]
      #   available: false                 # Allow switching to the theme [default=true]