all:
  sympal_config:

    admin_modules:
      sympal_themes: ~

  theme:
    # Disable/Enable theming globally
    enabled:           true
    
    manager_class:     sfThemeManager
    dispatcher_class:  sfThemeDispatcher

    # Configure the default theme to render
    default_theme:     default
    
    # Configure the theme to render for "admin" modules
    admin_theme:       admin
    
    # Configure whether or not to allow the theme to be changed with a 
    # parameter in the url named sf_sympal_theme. Example: ?sf_sympal_theme=wordpress_default
    # The value will also be remembered in the users session
    allow_changing_theme_by_url: true
    theme_request_parameter_name: sf_sympal_theme
    
    # Specify an array of modules and the theme that each should use
    modules:    []
      # my_module:     theme_name
    
    # Specify an array of routes and the theme that each should use
    routes:     []
      # my_route:      theme_name
  
  themes:
    # my_theme:
    #   available: false       # Don't show in the list of available themes to switch to
    #   disabled: false
    #   layout:   my_theme
    #   admin_generator_class: sfSympalDoctrineGenerator
    #   admin_generator_theme: sympal_admin
    #   javascripts:
    #     - /sfSympalPlugin/js/jQuery.cookie.js
    #   stylesheets:
    #     - /sfSympalPlugin/fancybox/jquery.fancybox.css
    #   callables:
    #     - [sfSympalToolkit, useJQuery]
